#!/usr/bin/env python3
"""Fetch achyuthhacks.substack.com/feed and rebuild _includes/substack-feed.html.

Stays inside the Python stdlib so the GitHub Action needs zero `pip install`.
"""

from __future__ import annotations

import html
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from email.utils import parsedate_to_datetime
from pathlib import Path

FEED_URL = "https://achyuthhacks.substack.com/feed"
OUTPUT = Path(__file__).resolve().parent.parent / "_includes" / "substack-feed.html"
DISPLAY_COUNT = 5
SNIPPET_CHARS = 220


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "amadabhu.github.io feed refresher"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def strip_html(s: str) -> str:
    s = re.sub(r"<[^>]+>", "", s)
    s = html.unescape(s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


def truncate(text: str, limit: int) -> str:
    if len(text) <= limit:
        return text
    cut = text[: limit].rsplit(" ", 1)[0]
    return cut.rstrip(",.;:") + "…"


def parse_date(raw: str | None) -> str:
    if not raw:
        return ""
    try:
        dt = parsedate_to_datetime(raw)
    except (TypeError, ValueError):
        return ""
    return dt.strftime("%b %-d, %Y") if dt else ""


def main() -> int:
    raw = fetch(FEED_URL)
    root = ET.fromstring(raw)

    items = root.findall(".//item")[:DISPLAY_COUNT]
    if not items:
        print("No <item> entries found in feed; aborting.", file=sys.stderr)
        return 1

    rendered = []
    for item in items:
        title = (item.findtext("title") or "Untitled").strip()
        link = (item.findtext("link") or "https://achyuthhacks.substack.com/").strip()
        pub_date = parse_date(item.findtext("pubDate"))
        description = item.findtext("description") or ""
        snippet = truncate(strip_html(description), SNIPPET_CHARS)

        rendered.append(
            "  <li>\n"
            f'    <a class="substack-feed__title" href="{html.escape(link)}" rel="noopener">{html.escape(title)}</a>\n'
            f'    <div class="substack-feed__meta">{html.escape(pub_date)}</div>\n'
            f'    <p class="substack-feed__snippet">{html.escape(snippet)}</p>\n'
            "  </li>"
        )

    body = (
        f"<!-- Auto-generated by scripts/build_substack_feed.py at "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}. Do not edit by hand. -->\n"
        '<ul class="substack-feed">\n'
        + "\n".join(rendered)
        + "\n</ul>\n"
    )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(body, encoding="utf-8")
    print(f"Wrote {OUTPUT} ({len(items)} entries).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
